### ISSUE TITLE
Release as a Universal Python Wheel

### ISSUE THREAD

**Issue by marcofavorito** [lark-parser/lark#529]
Hi, 

I noticed the software is not released as a (Pure-)Python Wheel. It could be useful in some contexts where a wheel is needed (e.g. installing the package with `micropip`, see (https://pyodide.readthedocs.io/en/latest/pypi.html#installing-packages-from-pypi)[https://pyodide.readthedocs.io/en/latest/pypi.html#installing-packages-from-pypi]

I think that is trivial to build a (universal) wheel for this project, since there are no dependencies and there are no C extensions.

**Comment by erezsh** [comment]
Not sure what you mean by "pure python". Can you elaborate?

**Comment by marcofavorito** [comment]
Thanks for the prompt response!

Here's the definition for Universal Wheel: [https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels](https://packaging.python.org/guides/distributing-packages-using-setuptools/#universal-wheels)

**Comment by erezsh** [comment]
Done. Let me know if it works.

**Comment by marcofavorito** [comment]
Yes, it worked. Tested the installation in Pyodide with the following revision:
https://github.com/iodide-project/iodide/tree/1d87c1a1c8e3bc6badb93ca334b9e0a98a46fbe1

![image](https://user-images.githubusercontent.com/9467617/76141956-0a5e3480-6069-11ea-8258-03657e5a46b4.png)

Thanks a lot :-)

**Comment by erezsh** [comment]
Happy to help :)

**Comment by youtux** [comment]
Hi, I see that the latest versions of lark-parser are still missing the wheel files.
Can you publish the next releases with wheels?
